### ISSUE TITLE
We're encountering a fatal error when releasing the new version of Transfer, and the error originates php-packages > License

### ISSUE THREAD

**Issue by surajkrsingh** [easily-amused/php-packages#15]
WP Version 6.6.1
Transfer 1.6.1

https://github.com/easily-amused/php-packages/blame/ec8dae4719aa6a58b230e47cf32d3a3a10771947/Licensing/License.php#L143

See here - https://go.screenpal.com/watch/cZj32vV9sFh

`Fatal error: Uncaught TypeError: array_filter(): Argument #1 ($array) must be of type array, bool given in /Users/surajsingh/Local Sites/learndash/app/public/wp-content/plugins/ea-transfer/vendor/easily-amused/php-packages/Licensing/License.php:143 Stack trace: #0 /Users/surajsingh/Local Sites/learndash/app/public/wp-content/plugins/ea-transfer/vendor/easily-amused/php-packages/Licensing/License.php(143): array_filter(true, Object(Closure)) #1 /Users/surajsingh/Local Sites/learndash/app/public/wp-content/plugins/ea-transfer/ea-transfer.php(117): EA\Licensing\License->__construct('Transfer', 19178, 'ea-transfer-set...', '/Users/surajsin...', '1.6.1', false) #2 /Users/surajsingh/Local Sites/learndash/app/public/wp-settings.php(522): include_once('/Users/surajsin...') #3 /Users/surajsingh/Local Sites/learndash/app/public/wp-config.php(94): require_once('/Users/surajsin...') #4 /Users/surajsingh/Local Sites/learndash/app/public/wp-load.php(50): require_once('/Users/surajsin...') #5 /Users/surajsingh/Local Sites/learndash/app/public/wp-admin/admin.php(34): require_once('/Users/surajsin...') #6 /Users/surajsingh/Local Sites/learndash/app/public/wp-admin/plugins.php(10): require_once('/Users/surajsin...') #7 {main} thrown in /Users/surajsingh/Local Sites/learndash/app/public/wp-content/plugins/ea-transfer/vendor/easily-amused/php-packages/Licensing/License.php on line 143

Note: Checked with options `honors_license_key` empty or not in options table.
`

**Comment by surajkrsingh** [comment]
Discussion and temporary solution thread - https://easily-amused.slack.com/archives/C046X1TJASF/p1724861278566109
